install.packages("tidyverse")
library(tidyverse)


# Main Path for getting the data in the form of CSVs
Main <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series"

# We are saving the links to each CSVs in separate objects
confirmed_Path <-  file.path(Main,"time_series_covid19_confirmed_global.csv")

Deaths_Path <- file.path(Main,"time_series_covid19_deaths_global.csv")

Recoverd_Path<- file.path(Main,"time_series_covid19_recovered_global.csv")


# Now, we are reading the data stored in each link
ConfirmedData <- read.csv(confirmed_Path,stringsAsFactors = FALSE) %>% arrange(Country.Region)
DeathData     <- read.csv(Deaths_Path,stringsAsFactors = FALSE) %>% arrange(Country.Region)
RecoveredData <- read.csv(Recoverd_Path,stringsAsFactors = FALSE) %>% arrange(Country.Region)



# Based on the region, the information will be fetched and prepared
Region <- "Pakistan"

# This function is important for making the data to be used in animations generated by Plotly
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat) 
  lvls <- plotly:::getLevels(var) 
  dats <- lapply(seq_along(lvls), 
                 function(x) {
                   cbind.data.frame(dat[var %in% lvls[seq(1, x)], ],
                                    frame = lvls[[x]])}) 
  dplyr::bind_rows(dats)}

# This DataClean function is requried to change the wide table into long table and then filtering the data according to region mentioned above
DataClean <- function(data, region, CaseType) {
  CleanedData <- data %>% 
    pivot_longer(cols = starts_with("X"), 
                 names_to = "Date", 
                 names_prefix = "X", 
                 names_ptypes = list(week = integer()), 
                 values_to = CaseType, 
                 values_drop_na = TRUE)   %>% 
    mutate(Province.State = ifelse(Province.State %in% "", Country.Region, Province.State)) %>% 
    mutate(Date = as.Date(Date, "%m.%d.%y")) %>% 
    filter(Province.State == region) %>% 
    arrange(Date) %>% 
    mutate(ID = row_number()) 
  return(CleanedData)
}

# Now we are cleaning data for each case
ConData <- DataClean(ConfirmedData,Region,"Confirmed") 

RecData <- DataClean(RecoveredData,Region,"Recovered") %>% select(ID,Recovered) 

DeData <-DataClean(DeathData,Region,"Deaths")          %>% select(ID,Deaths)


# In this code we are going to merge the cleaned data according to the ID column
AllData <- list(ConData, RecData, DeData)              %>% reduce(left_join, by = "ID")


# In this code, we are generating the frames for animations.
frames <- AllData %>% accumulate_by(~ID)


# You have to change this path according to your setup
flexdash_path <- "C:/Users/rehan/Desktop/flexdashboard"  
write.csv(ConfirmedData,file.path(flexdash_path, "ConfirmedData.csv"), row.names = FALSE)
write.csv(RecoveredData,file.path(flexdash_path, "RecoveredData.csv"), row.names = FALSE)
write.csv(DeathData,file.path(flexdash_path, "DeathData.csv"), row.names = FALSE)
write.csv(AllData,file.path(flexdash_path, "AllData.csv"), row.names = FALSE)
write.csv(frames,file.path(flexdash_path, "frames.csv"), row.names = FALSE)











